# Generated by Django 5.0.6 on 2025-05-10 17:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tienda', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producto',
            name='categoria',
            field=models.CharField(choices=[('herramientas', 'Herramientas'), ('materiales', 'Materiales'), ('accesorios', 'Accesorios'), ('pinturas', 'Pinturas'), ('electricidad', 'Electricidad')], max_length=100),
        ),
        migrations.AlterField(
            model_name='producto',
            name='imagen',
            field=models.ImageField(upload_to='static/productos/'),
        ),
    ]
