# Generated by Django 5.0.6 on 2025-05-22 01:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tienda', '0007_ordendespacho'),
    ]

    operations = [
        migrations.AddField(
            model_name='pedido',
            name='datos_compra',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='tienda.datoscompra'),
        ),
    ]
