# Generated by Django 5.0.6 on 2025-05-27 04:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tienda', '0009_producto_activo_alter_pedido_estado'),
    ]

    operations = [
        migrations.AddField(
            model_name='ordendespacho',
            name='motivo_rechazo',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='ordendespacho',
            name='estado',
            field=models.CharField(choices=[('pendiente', 'Pendiente'), ('preparando', 'Preparando'), ('listo', 'Listo para entregar'), ('enviado', 'Enviado'), ('entregado', 'Entregado')], default='pendiente', max_length=20),
        ),
        migrations.AlterField(
            model_name='producto',
            name='categoria',
            field=models.CharField(choices=[('herramientas', 'Herramientas'), ('herramientas_electricas', 'Herramientas Eléctricas'), ('herramientas_manuales', 'Herramientas Manuales'), ('materiales', 'Materiales'), ('accesorios', 'Accesorios'), ('pinturas', 'Pinturas'), ('electricidad', 'Electricidad'), ('inalambricas', 'Inalámbricas'), ('medicion', 'Medición')], max_length=100),
        ),
        migrations.DeleteModel(
            name='TransferenciaPago',
        ),
    ]
