# Generated by Django 5.0.6 on 2025-06-24 23:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tienda', '0010_ordendespacho_motivo_rechazo_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pedido',
            name='estado',
            field=models.CharField(choices=[('pendiente', 'Pendiente'), ('aprobado', 'Aprobado'), ('rechazado', 'Rechazado'), ('en_preparacion', 'En preparación'), ('enviado', 'Enviado'), ('en_tienda', 'En tienda'), ('entregado', 'Entregado'), ('finalizado', 'Finalizado')], default='pendiente', max_length=20),
        ),
    ]
